Add apartment form repository
KoalicjaOtwartyKrakow/flutter-android pull request #29
Opened 2022-03-15 00:44 UTC by koral--

Fix accommodation tests

2022-03-15 10:56 UTC, Pablo1785 requested changes
Please rename Apartment to Accomodation in new class and file names to keep things consistent

2022-03-15 19:07 UTC, koral-- commented
done

2022-03-17 17:13 UTC, Pablo1785 requested changes

2022-03-17 17:13 UTC, Pablo1785 commented on lib/presentation/host/widgets/apartment_form.dart
> +          } else if (state is SubmitFailure) {
You can use state.maybeMap(submitSuccess: (state) {}, someDifferentApartmentFormState: (state){}, otherOneOfMyApartmentFormStates: (state) {}, orElse: () {}) to handle select ApartmentFormStates without making SubmitFailure a public type

2022-03-17 17:13 UTC, Pablo1785 commented on lib/application/apartment_form/apartment_form_state.dart
> +  const factory ApartmentFormState.submitFailure(Failure failure) = SubmitFailure;
Should be _SubmitFailure and _SubmitFailure should not be used directly anywhere else, instead use state.map() wherever you need to check all possible states and state.maybeMap() wherever you only need to check for some of the states

2022-03-17 17:13 UTC, Pablo1785 commented on lib/application/accommodation_form/accommodation_form_state.dart
> +  const factory AccommodationFormState.submitFailure(Failure failure) = SubmitFailure;
Should be _SubmitFailure and shouldnt be used outside of this definition

2022-03-17 17:13 UTC, Pablo1785 commented on test/application/accomodation_loader/accomodation_loader_bloc_test.dart
> +        const AccommodationLoaderState.initial(),
The bloc is renamed here but there are no changes to its definition, this should be all red in the IDE/tests

Please revert changes to this file or rename the AccomodationLoader to AccommodationLoader as well

2022-03-17 23:35 UTC, merged